- hosts: master[0]
  become: yes
  roles:
    - crio
    - k8s-install
    # - master-config
    - kubeadm-init
    - kubectl-enable
    - cni-install

# - hosts: master[1:]
#   become: yes
#   roles:
#     - docker
#     - k8s-install
#     - master-config
#     - master-join
#     - kubectl-enable

- hosts: worker
  become: yes
  roles:
    - crio
    - k8s-install
    - worker-join