- name: Create .kube directory
  file:
    path: ~/.kube
    state: directory

- name: Copy admin.conf to .kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    remote_src: yes

- name: Change owner of .kube/config
  shell: |
    chown $(id -u):$(id -g) $HOME/.kube/config

- name: Enable kubectl
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf